export const SET_FILTER = "SET_FILTER"
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const GET_FILTRED_COUNTRIES = "GET_FILTRED_COUNTRIES"
export const GET_SEARCHED_COUNTRIES = "GET_SEARCHED_COUNTRIES"
 
 